# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Vim4Robotics
nav:
  - index.md
  - installation.md
  - latex.md
theme:
  name: material
  # logo: assets/logo.png
  # favicon: assets/logo.png
  features:
    - navigation.instant
    - navigation.top
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - stylesheets/extra.js
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
